from typing import Protocol

class RobotBackend(Protocol):
    def read_state(self): ...
    def send_body_command(self, command) -> None: ...
    def send_hand_command(self, command) -> None: ...
    def health(self) -> dict: ...
